# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        apt-get update
        apt-get upgrade -y
        ./compile-libks.sh
        ./compile-signalwire-c.sh
        ./compile-freeswitch.sh
        ./upload_packages_s3.sh
      env:
        AWS_REGION: eu-west-2
        AWS_S3_BUCKET: etech-pro-apt-repo
        APTLY_REPO_NAME: apt-repo.etechpro.co.uk
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GPG_SECRET_ARN: ${{ secrets.GPG_SECRET_ARN}}
