# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: eu-west-2
  AWS_S3_BUCKET: etech-pro-apt-repo
  APTLY_REPO_NAME: apt-repo.etechpro.co.uk
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GPG_SECRET_ARN: ${{ secrets.GPG_SECRET_ARN}}


jobs:

  build:

    runs-on: self-hosted


    steps:

    - uses: actions/checkout@v2


    - name: Run a multi-line script
      run: |
        apt-get update
        apt-get upgrade -y
        ./compile-libks.sh
        ./compile-signalwire-c.sh
        ./compile-freeswitch.sh
        ./upload_packages_s3.sh
